<form method="get" action="index.php">
    <fieldset>
        <label>firstName</label>
        <input type="texte">
          </fieldset>
          
          <fieldset>
        <label>lastName</label>
        <input type="texte">
          </fieldset>
          
          <fieldset>
        <label>email</label>
        <input type="email">
          </fieldset>
          
          <fieldset>
        <label>password</label>
        <input type="password">
          </fieldset>
          
          <fieldset>
        <label>confirmPassword</label>
        <input type="password">
          </fieldset>
          
          <fieldset>
        <label>formName</label>
        <input type="hidden">
          </fieldset>
    
</form>
